// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ICarbonCheckmarkFilled: typeof import('~icons/carbon/checkmark-filled')['default']
    ICarbonLanguage: typeof import('~icons/carbon/language')['default']
    ICarbonMoon: typeof import('~icons/carbon/moon')['default']
    ICarbonRadioButton: typeof import('~icons/carbon/radio-button')['default']
    ICarbonSun: typeof import('~icons/carbon/sun')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}

export {}
