// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core';

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    'IconCarbon:logoGithub': typeof import('~icons/carbon/logo-github')['default'];
    IconCarbonLanguage: typeof import('~icons/carbon/language')['default'];
    IconCarbonMoon: typeof import('~icons/carbon/moon')['default'];
    IconCarbonSun: typeof import('~icons/carbon/sun')['default'];
    RouterLink: typeof import('vue-router')['RouterLink'];
    RouterView: typeof import('vue-router')['RouterView'];
  }
}

export {};
